version: '3.8'

services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/orderdb
      - REDIS_URL=redis://redis:6379
      - REDIS_TTL_SECONDS=3600
      - WAREHOUSE_LIMIT_DAYS=3
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
