version: '3.8'

services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/orderdb
      - WAREHOUSE_LIMIT_DAYS=3
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
